apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnect
metadata:
  name: mq-connect
  namespace: es
  annotations:
    eventstreams.ibm.com/use-connector-resources: "true"
spec:
  replicas: 1
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
    limits:
      cpu: 2000m
      memory: 2Gi
  bootstrapServers: prod-3-brokers-kafka-bootstrap:9093 
  image: default-route-openshift-image-registry.mycluster-syd01-c3c-32x64-4c1a443ebaec2dc527b196dee1db66b5-0000.au-syd.containers.appdomain.cloud/mqpod/kafkaconnectwithmq:latest-134
  template:
    pod:
      imagePullSecrets:
        - name: bbreg
      metadata:
        annotations:
          eventstreams.production.type: CloudPakForIntegrationNonProduction
          productID: 2a79e49111f44ec3acd89608e56138f5
          productName: IBM Event Streams for Non Production
          productVersion: 11.1.5
          productMetric: VIRTUAL_PROCESSOR_CORE
          productChargedContainers: my-connect-cluster-connect
          cloudpakId: c8b82d189e7545f0892db9ef2731b90d
          cloudpakName: IBM Cloud Pak for Integration
          productCloudpakRatio: "2:1"
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets-distributed
    config.storage.topic: connect-cluster-configs-distributed
    status.storage.topic: connect-cluster-status-distributed
    config.storage.replication.factor: 3
    offset.storage.replication.factor: 3
    status.storage.replication.factor: 3
    config.providers: file
    config.providers.file.class: org.apache.kafka.common.config.provider.DirectoryConfigProvider
  tls:
    trustedCertificates:
      - secretName: prod-3-brokers-cluster-ca-cert
        certificate: ca.crt
  authentication:
    type: tls
    certificateAndKey:
      certificate: user.crt
      key: user.key
      secretName: usertls 
  externalConfiguration:
    volumes:
      - name: jms-client-keystore
        secret:
          secretName: jms-client-keystore
      - name: jms-client-truststore
        secret:
          secretName: jms-client-truststore
