apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaConnector
metadata:
  name: mq-connector
  namespace: es
  labels:
    eventstreams.ibm.com/cluster: mq-connect
spec:
  class: com.ibm.eventstreams.connect.mqsource.MQSourceConnector
  tasksMax: 1
  config:
    # the Kafka topic to produce to
    topic: ivt1
    # the MQ queue to get messages from
    mq.queue: IVT.Q 
    # messages sent to the MQ queue are JMS TextMessages
    mq.message.body.jms: true
    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter
    mq.record.builder: com.ibm.eventstreams.connect.mqsource.builders.DefaultRecordBuilder
    # connection details for the queue manager
    mq.queue.manager: QM1CP4I1
    mq.connection.name.list: mq1-ibm-mq-qm-mq.mycluster-syd01-c3c-32x64-4c1a443ebaec2dc527b196dee1db66b5-0000.au-syd.containers.appdomain.cloud(443)
    mq.channel.name: TLSS
    mq.user.name: ivt 
    mq.password: password
    # SSL config for connecting to MQ
    mq.ssl.use.ibm.cipher.mappings: false 
    mq.ssl.cipher.suite: '*TLS12'
    mq.ssl.truststore.location: /opt/kafka/external-configuration/jms-client-truststore/tls.jks
    mq.ssl.truststore.password: ${file:/opt/kafka/external-configuration/jms-client-truststore:password}
    # mq.ssl.keystore.location: /opt/kafka/external-configuration/jms-client-keystore/tls.jks
    # mq.ssl.keystore.password: ${file:/opt/kafka/external-configuration/jms-client-keystore:password}
