apiVersion: eventstreams.ibm.com/v1beta2
kind: KafkaTopic
metadata:
  name: orders
  namespace: ap-southeast-4
  labels:
    eventstreams.ibm.com/cluster: ap4-eventstreams
spec:
  config:
    min.insync.replicas: '1'
    retention.bytes: '100000000'
  partitions: 3
  replicas: 3
  topicName: LH.ORDERS